version: '3'
services:
  app:
    command: bundle exec puma -C config/puma.rb
    depends_on:
      - db
  db:
    image: mysql:8.0
    env_file:
      - ./environment/db.env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - Karibito-network
  web:
    ports:
      - 3000:80