version: '3'
services:
  app:
    build:
      context: .
    env_file:
      - ./environment/db.env
    command: bundle exec puma -C config/puma.rb -e production
    volumes:
      - .:/myapp
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
      - log-data:/myapp/log
    environment:
      - EDITOR=vim
    networks:
      - Karibito-network
    tty: true
    stdin_open: true
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - Karibito-network
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:

networks:
  Karibito-network:
    external: true