default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: <%= ENV.fetch('DEFAULT_USER') { 'root' } %>
  password: <%= ENV.fetch('DEFAULT_PASSWORD') { 'password' } %>
  host: <%= ENV.fetch('DEFAULT_HOST') { 'db' } %>

development:
  <<: *default
  database: karibito_development
test:
  <<: *default
  database: karibito_test

production:
  <<: *default
  database: karibito_production
  host: <%= ENV['KARIBITO_HOST'] %>
  username: <%= ENV['KARIBITO_USER'] %>
  password: <%= ENV['KARIBITO_PASSWORD'] %>